winget install "XP9KHM4BK9FZ7Q"
winget install "Google.Chrome"
winget install "Mozilla.Firefox"
winget install "CodecGuide.K-LiteCodecPack.Full"
winget install "Python.Python.3.10"
winget install "CPUID.CPU-Z"
winget install "RARLab.WinRAR"
winget install "Git.Git"
winget install "GitHub.cli"
winget install "9P03BZ82L9F2"
winget install "AutoHotkey.AutoHotkey"
winget install "PowerSoftware.PowerISO"
winget install "c0re100.qBittorrent-Enhanced-Edition"
winget install "Tonec.InternetDownloadManager"
winget install "ProtonTechnologies.ProtonVPN"
winget install "Valve.Steam"
pause